import type { MigrationReport } from './types.js';

/**
 * Generate a GitHub-flavored Markdown migration report.
 */
export function generateMarkdownReport(report: MigrationReport): string {
  const lines: string[] = [];

  lines.push('# StrapiShift Migration Report');
  lines.push(`Generated: ${report.generatedAt}`);
  lines.push(`Source: Strapi ${report.sourceVersion} → Target: Strapi ${report.targetVersion}`);
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push(`- **Content Types:** ${report.summary.totalContentTypes}`);
  lines.push(
    `- **Status:** ${report.summary.clean} clean | ${report.summary.warnings} warnings | ${report.summary.blockers} blockers`,
  );
  lines.push(`- **Total Findings:** ${report.summary.totalFindings}`);
  lines.push(`- **Migration Readiness:** ${report.summary.migrationReadiness}%`);
  lines.push(
    `- **Estimated Effort:** ${report.summary.estimatedEffort.totalHoursMin}–${report.summary.estimatedEffort.totalHoursMax} hours`,
  );
  lines.push('');

  // Blockers first
  const blockerTypes = report.contentTypes.filter((ct) => ct.status === 'blocker');
  if (blockerTypes.length > 0) {
    lines.push('## Blockers (Resolve Before Migration)');
    lines.push('');
    for (const ct of blockerTypes) {
      lines.push(`### ${ct.name}`);
      for (const f of ct.findings.filter((f) => f.severity === 'blocker')) {
        lines.push(
          `- [ ] **[BLOCKER]** ${f.field ? `\`${f.field}\`` : ct.name}: ${f.title}`,
        );
        lines.push(`  - Action: ${f.action}`);
        lines.push(`  - Effort: ${f.effort}`);
        if (f.docsUrl) lines.push(`  - Docs: ${f.docsUrl}`);
      }
      lines.push('');
    }
  }

  // Warnings
  const warningTypes = report.contentTypes.filter((ct) => ct.status === 'warning');
  if (warningTypes.length > 0) {
    lines.push('## Warnings');
    lines.push('');
    for (const ct of warningTypes) {
      lines.push(`### ${ct.name}`);
      for (const f of ct.findings.filter((f) => f.severity === 'warning')) {
        lines.push(
          `- [ ] **[WARNING]** ${f.field ? `\`${f.field}\`` : ct.name}: ${f.title}`,
        );
        lines.push(`  - Action: ${f.action}`);
        lines.push(`  - Effort: ${f.effort}`);
        if (f.docsUrl) lines.push(`  - Docs: ${f.docsUrl}`);
      }
      lines.push('');
    }
  }

  // Clean types
  const cleanTypes = report.contentTypes.filter((ct) => ct.status === 'clean');
  if (cleanTypes.length > 0) {
    lines.push('## Clean (No Issues)');
    lines.push('');
    for (const ct of cleanTypes) {
      lines.push(`- ✅ ${ct.name} (${ct.fieldCount} fields, ${ct.relationCount} relations)`);
    }
    lines.push('');
  }

  // Checklist
  if (report.migrationChecklist.length > 0) {
    lines.push('## Migration Checklist');
    lines.push('');
    for (const phase of report.migrationChecklist) {
      lines.push(`### ${phase.phase}`);
      lines.push(phase.description);
      lines.push('');
      for (const item of phase.items) {
        lines.push(`- [ ] ${item.finding.title} (${item.finding.contentType}${item.finding.field ? `.${item.finding.field}` : ''})`);
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('*Generated by [StrapiShift](https://github.com/ICJIA/strapishift)*');

  return lines.join('\n');
}
