import type { ParityReport } from '../parity/types.js';

/**
 * Generate JSON parity report.
 */
export function generateParityJson(report: ParityReport): string {
  return JSON.stringify(report, null, 2);
}

/**
 * Generate Markdown parity report.
 */
export function generateParityMarkdown(report: ParityReport): string {
  const lines: string[] = [];

  lines.push('# StrapiShift Parity Verification Report');
  lines.push(`Generated: ${report.generatedAt}`);
  lines.push('');
  lines.push(`## Parity Score: ${report.parityScore}%`);
  lines.push(`- Checks: ${report.totalChecks}`);
  lines.push(`- Passed: ${report.passed}`);
  lines.push(`- Failed: ${report.failed}`);
  lines.push(`- Warnings: ${report.warnings}`);
  lines.push('');

  if (report.failures.length > 0) {
    lines.push('## Failures');
    lines.push('');
    for (const check of report.failures) {
      lines.push(`- [ ] **FAIL** ${check.contentType ? `${check.contentType}` : ''}${check.field ? `.${check.field}` : ''}: ${check.message}`);
    }
    lines.push('');
  }

  if (report.warningChecks.length > 0) {
    lines.push('## Warnings');
    lines.push('');
    for (const check of report.warningChecks) {
      lines.push(`- [ ] **WARN** ${check.contentType ? `${check.contentType}` : ''}${check.field ? `.${check.field}` : ''}: ${check.message}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by [StrapiShift](https://github.com/ICJIA/strapishift)*');
  return lines.join('\n');
}

/**
 * Generate CSV parity report.
 */
export function generateParityCsv(report: ParityReport): string {
  const headers = ['Check ID', 'Category', 'Content Type', 'Field', 'Status', 'Message', 'v3 Value', 'v5 Value'];
  const rows = report.checks.map((c) => [
    c.checkId,
    c.category,
    c.contentType || '',
    c.field || '',
    c.status,
    c.message,
    c.v3Value || '',
    c.v5Value || '',
  ]);

  const escape = (v: string) =>
    v.includes(',') || v.includes('"') || v.includes('\n') ? `"${v.replace(/"/g, '""')}"` : v;

  return [headers.map(escape).join(','), ...rows.map((r) => r.map(escape).join(','))].join('\n');
}

/**
 * Generate self-contained HTML parity report with printable fix checklist.
 */
export function generateParityHtml(report: ParityReport): string {
  const escapeHtml = (s: string) =>
    s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

  const failureRows = report.failures
    .map(
      (c) => `
      <tr>
        <td><input type="checkbox" class="print-checkbox"></td>
        <td>${escapeHtml(c.contentType || '')}</td>
        <td><code>${escapeHtml(c.field || '—')}</code></td>
        <td><span class="badge fail">FAIL</span></td>
        <td>${escapeHtml(c.message)}</td>
      </tr>`,
    )
    .join('');

  const warningRows = report.warningChecks
    .map(
      (c) => `
      <tr>
        <td><input type="checkbox" class="print-checkbox"></td>
        <td>${escapeHtml(c.contentType || '')}</td>
        <td><code>${escapeHtml(c.field || '—')}</code></td>
        <td><span class="badge warn">WARN</span></td>
        <td>${escapeHtml(c.message)}</td>
      </tr>`,
    )
    .join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>StrapiShift Parity Report — ${report.parityScore}%</title>
<style>
  :root { --bg: #0f172a; --text: #e2e8f0; --card-bg: #1e293b; --border: #334155; }
  .light { --bg: #fff; --text: #1e293b; --card-bg: #f8fafc; --border: #e2e8f0; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: var(--bg); color: var(--text); padding: 2rem; max-width: 1000px; margin: 0 auto; }
  h1 { margin-bottom: 0.25rem; }
  .score { font-size: 3rem; font-weight: 800; margin: 1rem 0; }
  .score.perfect { color: #22C55E; }
  .score.good { color: #EAB308; }
  .score.poor { color: #EF4444; }
  .stats { display: flex; gap: 2rem; margin-bottom: 2rem; color: #94a3b8; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 2rem; }
  th, td { text-align: left; padding: 0.6rem; border-bottom: 1px solid var(--border); font-size: 0.9rem; }
  th { color: #94a3b8; font-weight: 600; }
  code { background: rgba(255,255,255,0.1); padding: 1px 4px; border-radius: 3px; }
  .badge { font-size: 0.7rem; font-weight: 700; padding: 2px 6px; border-radius: 3px; }
  .badge.fail { background: #EF4444; color: white; }
  .badge.warn { background: #EAB308; color: #1e293b; }
  .theme-toggle { position: fixed; top: 1rem; right: 1rem; background: var(--card-bg); border: 1px solid var(--border); color: var(--text); padding: 0.4rem 0.8rem; border-radius: 4px; cursor: pointer; }

  @media print {
    body { background: white !important; color: #1e293b !important; padding: 1cm; font-size: 11pt; }
    .theme-toggle { display: none !important; }
    .score { color: #1e293b !important; }
    table { border: 1px solid #d1d5db; }
    th { background: #f3f4f6 !important; color: #374151 !important; }
    td { border-color: #d1d5db !important; }
    .badge { border: 1px solid; background: transparent !important; }
    .badge.fail { color: #dc2626 !important; border-color: #dc2626; }
    .badge.warn { color: #ca8a04 !important; border-color: #ca8a04; }
    code { background: #f3f4f6 !important; }
    .stats { color: #6b7280 !important; }
    input[type="checkbox"] { appearance: none; -webkit-appearance: none; width: 14px; height: 14px; border: 1.5px solid #6b7280; display: inline-block; vertical-align: middle; }
  }
</style>
</head>
<body>
<button class="theme-toggle" onclick="document.body.classList.toggle('light')">🌓 Toggle Theme</button>
<h1>StrapiShift Parity Report</h1>
<p style="color:#94a3b8">Generated: ${escapeHtml(report.generatedAt)}</p>
<div class="score ${report.parityScore === 100 ? 'perfect' : report.parityScore >= 80 ? 'good' : 'poor'}">${report.parityScore}% Parity</div>
<div class="stats">
  <span>✅ ${report.passed} passed</span>
  <span>❌ ${report.failed} failed</span>
  <span>⚠️ ${report.warnings} warnings</span>
  <span>Total: ${report.totalChecks} checks</span>
</div>

${
  report.failures.length > 0
    ? `<h2>Fix Checklist — Failures</h2>
<table>
  <thead><tr><th style="width:30px">☐</th><th>Content Type</th><th>Field</th><th>Status</th><th>Issue</th></tr></thead>
  <tbody>${failureRows}</tbody>
</table>`
    : ''
}

${
  report.warningChecks.length > 0
    ? `<h2>Warnings</h2>
<table>
  <thead><tr><th style="width:30px">☐</th><th>Content Type</th><th>Field</th><th>Status</th><th>Issue</th></tr></thead>
  <tbody>${warningRows}</tbody>
</table>`
    : ''
}

<p style="color:#64748b; font-size:0.85rem; margin-top:2rem;">Generated by StrapiShift — github.com/ICJIA/strapishift</p>
</body>
</html>`;
}
